### PR TITLE
Storybookjs Init

### PR DESCRIPTION
**Pull request by lovincyrus**
## Storybookjs init with vue
* init storybookjs
* set up vue template
* add .gitignore
* start fresh with 0.5.0
* salvaged package.json and license
* add new storybookjs README.md

### CODE REVIEW

**Comment by lovincyrus** [comment]
image

**Comment by nylira** [comment]
That was fast! This is what you were talking about @fadeev about how this is an unstyled component. @nassdonald would like to hear what you think about default component styles, whether they should be in the component or in the application (and what defaults make sense).

**Comment by nassdonald** [comment]
This is great! 👏  I will have to play around with this repo properly before I can give any thoughts on the technical side of things.

In my experience, there are two main approaches to default component styling. It's simply a case of decided how opinionated we want the component to be out-of-the-box.

One approach is to style the component to a finished, usable state and allow each app to override styling with use of variables, classnames, and configuration options when instantiating or injecting the component. [Bootstrap](https://getbootstrap.com/) is a typical example of this.

The other approach is to apply the bear minimum styling required to make the component work. For example, with a tooltip this might be fixed positioning and hidden/visible states styling. Then each application would apply its own styling however it sees fit.

The former approach certainly offers us a quicker means of using the components across many projects with little to no configuration. However, the latter gives us much more flexibility in how these components are styled.

Let's discuss this in more detail together and review examples of where one approach may be preferred over the other.

**Comment by fadeev** [comment]
There is also a middleground, where you have your unstyled component and a second one, which imports the first one and adds styles.

**Comment by nassdonald** [comment]
That's a very good point. We could create a hard separation between styles and logic/behaviour to have the best of both worlds. The challenge comes (from my experience) in trying to add custom behaviour or styling when an override simply isn't clean enough, or in some cases, completely impossible without forking.

**Comment by nylira** [comment]
I like the Bootstrap approach because I don't see us having to deviate much from one standard design (especially as a very small team). The flexibilty of having to write extra CSS per website per component, or alternatively a set of extra components for styling, doesn't seem worth the added complexity.

I think that if all of our websites shared the same visual look and feel, and only differed by theme colors, iconography, and imagery -- that would be just fine.

**Comment by fadeev** [comment]
Added modal component and switched to CSF as per the docs.

https://storybook.js.org/docs/formats/component-story-format/

**Pull request merged**
